stages:
  - build
  - deploy

esp32_v4.3_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  tags:
    - build

  variables:
    GIT_STRATEGY: clone

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v4.3 ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - python -m pip install -r $IDF_PATH/requirements.txt
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - idf.py set-target esp32
    - idf.py build

    - rm -rf build sdkconfig
    - idf.py set-target esp32
    - echo -e "CONFIG_ESP_MODEM_ENABLE=y\nCONFIG_SET_VENDOR_IE=y\nCONFIG_AP_CUSTOM_IP=y\nCONFIG_ENABLE_SOFTAP_FOR_WIFI_CONFIG=y" >> sdkconfig.defaults.esp32
    - idf.py build

esp32_v4.4_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env:v4.4-1
  tags:
    - build

  variables:
    GIT_STRATEGY: clone

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v4.4 ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - python -m pip install -r $IDF_PATH/requirements.txt
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - idf.py set-target esp32
    - idf.py build

    - rm -rf build sdkconfig
    - idf.py set-target esp32
    - echo -e "CONFIG_ESP_MODEM_ENABLE=y\nCONFIG_SET_VENDOR_IE=y\nCONFIG_AP_CUSTOM_IP=y\nCONFIG_ENABLE_SOFTAP_FOR_WIFI_CONFIG=y" >> sdkconfig.defaults.esp32
    - idf.py build

esp32c3_v4.4_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env:v4.4-1
  tags:
    - build

  variables:
    GIT_STRATEGY: clone

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v4.4 ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - python -m pip install -r $IDF_PATH/requirements.txt
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - idf.py set-target esp32c3
    - idf.py build

    - rm -rf build sdkconfig
    - idf.py set-target esp32c3
    - echo -e "CONFIG_SET_VENDOR_IE=y\nCONFIG_AP_CUSTOM_IP=y\nCONFIG_ENABLE_SOFTAP_FOR_WIFI_CONFIG=y" >> sdkconfig.defaults.esp32c3
    - idf.py build

esp32s2_v4.4_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env:v4.4-1
  tags:
    - build

  variables:
    GIT_STRATEGY: clone

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v4.4 ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - python -m pip install -r $IDF_PATH/requirements.txt
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - idf.py set-target esp32s2
    - idf.py build

    - rm -rf build sdkconfig
    - idf.py set-target esp32s2
    - echo -e "CONFIG_SET_VENDOR_IE=y\nCONFIG_AP_CUSTOM_IP=y\nCONFIG_ENABLE_SOFTAP_FOR_WIFI_CONFIG=y" >> sdkconfig.defaults.esp32s2
    - idf.py build

esp32s3_v4.4_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env:v4.4-1
  tags:
    - build

  variables:
    GIT_STRATEGY: clone

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v4.4 ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - python -m pip install -r $IDF_PATH/requirements.txt
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - idf.py set-target esp32s3
    - idf.py build

    - rm -rf build sdkconfig
    - idf.py set-target esp32s3
    - echo -e "CONFIG_SET_VENDOR_IE=y\nCONFIG_AP_CUSTOM_IP=y\nCONFIG_ENABLE_SOFTAP_FOR_WIFI_CONFIG=y" >> sdkconfig.defaults.esp32s3
    - idf.py build

esp32_master_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env:v4.4-1
  tags:
    - build

  variables:
    GIT_STRATEGY: clone

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b master ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - python -m pip install -r $IDF_PATH/requirements.core.txt
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - idf_tools.py install-python-env
    - cd ..

    - idf.py set-target esp32
    - idf.py build

    - rm -rf build sdkconfig
    - idf.py set-target esp32
    - echo -e "CONFIG_SET_VENDOR_IE=y\nCONFIG_AP_CUSTOM_IP=y\nCONFIG_ENABLE_SOFTAP_FOR_WIFI_CONFIG=y" >> sdkconfig.defaults.esp32
    - idf.py build

push_master_to_github:
  stage: deploy
  only:
    - master
    - /^release\/v/
#  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
    GITHUB_PUSH_REFS: refs/remotes/origin/release refs/remotes/origin/master
  before_script:
    - echo "skip default before_script"
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/esp-gateway.git
    - eval $(git for-each-ref --shell bash --format 'if [ $CI_BUILD_REF == %(objectname) ]; then git checkout -B %(refname:strip=3); git push --follow-tags github %(refname:strip=3); fi;' $GITHUB_PUSH_REFS)
